#!/bin/bash
# Lab2 runner
catkin_workspace=/home/saydos/Desktop/ros/catkin_ws
# roscore
gnome-terminal --window -e "/bin/bash -c 'roscore; exec /bin/bash -i'"
# bookkeeper
gnome-terminal --window -e "/bin/bash -c 'cd $catkin_workspace; source ./devel/setup.sh; rosrun bookkeeper bookkeeper_node Jack Pit; exec /bin/bash -i'"
# room
gnome-terminal --window -e "/bin/bash -c 'cd $catkin_workspace; source ./devel/setup.sh; rosrun room room_node; exec /bin/bash -i'"
# add workers
while read first_name last_name salary; do gnome-terminal --window -e "/bin/bash -c 'cd $catkin_workspace; source ./devel/setup.sh; rosrun worker worker_node __name:=worker$first_name$last_name $first_name $last_name; exec /bin/bash -i'"; done < $catkin_workspace/src/bookkeeper/resources/worker_list.txt
